//! Bake the boot-splash logo + the desktop wallpaper into the kernel binary.
//!
//! Logo:
//!   1. Decode `assets/logo.png` to RGBA.
//!   2. Auto-crop the transparent margin so the visible glyph fills the frame.
//!   3. Resize preserving aspect ratio so the longest side == MAX_SIDE.
//!   4. Emit RGBA (4 bytes/pixel) → OUT_DIR/logo.bin + logo_consts.rs
//!
//! Wallpaper:
//!   1. Decode `assets/wallpaper.jpg` to RGB.
//!   2. Resize to "cover" 1280×720 (scale up to fill, then centre-crop).
//!   3. Emit packed RGB (3 bytes/pixel) → OUT_DIR/wallpaper.bin
//!      + WALLPAPER_W / WALLPAPER_H consts in wallpaper_consts.rs.
//!   The kernel blits this straight to the framebuffer as the desktop bg.

use std::path::PathBuf;

use image::{imageops::FilterType, GenericImageView, RgbaImage};

/// Longest side of the on-screen logo, in pixels.
const MAX_SIDE: u32 = 400;

/// Alpha cutoff for "the glyph is here" when computing the crop box.
/// Soft anti-aliased edges (alpha 1..=11) are treated as background.
const ALPHA_CUTOFF: u8 = 12;

/// Padding (in source pixels) added around the detected bounding box so we
/// don't crop into the glyph's anti-aliased halo.
const CROP_PAD: u32 = 4;

/// Target wallpaper dimensions — matches the default boot framebuffer.
const WALL_W: u32 = 1280;
const WALL_H: u32 = 720;

fn main() {
    let manifest_dir = PathBuf::from(std::env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let out_dir = PathBuf::from(std::env::var_os("OUT_DIR").expect("OUT_DIR"));

    let logo_src = manifest_dir.join("assets").join("logo.png");
    let wall_src = manifest_dir.join("assets").join("wallpaper.jpg");
    println!("cargo:rerun-if-changed={}", logo_src.display());
    println!("cargo:rerun-if-changed={}", wall_src.display());
    println!("cargo:rerun-if-changed=build.rs");

    let img = image::open(&logo_src)
        .unwrap_or_else(|e| panic!("failed to open {}: {}", logo_src.display(), e))
        .to_rgba8();

    let (sw, sh) = img.dimensions();
    let (bb_x, bb_y, bb_w, bb_h) = alpha_bbox(&img, ALPHA_CUTOFF).expect("logo is fully transparent");
    println!(
        "cargo:warning=logo bbox = ({},{}) {}x{} (of {}x{})",
        bb_x, bb_y, bb_w, bb_h, sw, sh
    );

    // Pad the bbox a touch, clamped to source bounds.
    let pad_x = CROP_PAD.min(bb_x);
    let pad_y = CROP_PAD.min(bb_y);
    let x = bb_x - pad_x;
    let y = bb_y - pad_y;
    let w = (bb_w + pad_x + CROP_PAD).min(sw - x);
    let h = (bb_h + pad_y + CROP_PAD).min(sh - y);

    let cropped = image::imageops::crop_imm(&img, x, y, w, h).to_image();

    // Scale preserving aspect ratio.
    let (target_w, target_h) = if w >= h {
        (MAX_SIDE, ((h as u64 * MAX_SIDE as u64) / w as u64) as u32)
    } else {
        (((w as u64 * MAX_SIDE as u64) / h as u64) as u32, MAX_SIDE)
    };

    let scaled = image::DynamicImage::ImageRgba8(cropped)
        .resize_exact(target_w, target_h, FilterType::Lanczos3)
        .to_rgba8();
    println!("cargo:warning=logo scaled to {}x{} (RGBA, {} KiB)",
             target_w, target_h, (target_w * target_h * 4) / 1024);

    // Emit raw RGBA — kernel does runtime alpha blending so the logo sits
    // naturally on any background.
    let mut rgba = Vec::with_capacity((target_w * target_h * 4) as usize);
    for pixel in scaled.pixels() {
        let [r, g, b, a] = pixel.0;
        rgba.extend_from_slice(&[r, g, b, a]);
    }

    let bin_path = out_dir.join("logo.bin");
    std::fs::write(&bin_path, &rgba).expect("write logo.bin");

    let consts_path = out_dir.join("logo_consts.rs");
    let consts = format!(
        "// auto-generated by kernel/build.rs — do not edit\n\
         pub const LOGO_W: usize = {};\n\
         pub const LOGO_H: usize = {};\n",
        target_w, target_h
    );
    std::fs::write(&consts_path, consts).expect("write logo_consts.rs");

    // ---------------- Wallpaper ----------------
    let wall = image::open(&wall_src)
        .unwrap_or_else(|e| panic!("failed to open {}: {}", wall_src.display(), e));
    let (sw, sh) = wall.dimensions();
    println!("cargo:warning=wallpaper source: {}x{}", sw, sh);

    // "Cover" fit: scale so the image fully covers WALL_W × WALL_H, then
    // centre-crop the overflow. This avoids letterboxing and preserves the
    // most interesting part of the image.
    let scale = (WALL_W as f32 / sw as f32).max(WALL_H as f32 / sh as f32);
    let scaled_w = (sw as f32 * scale).ceil() as u32;
    let scaled_h = (sh as f32 * scale).ceil() as u32;
    let scaled = wall.resize_exact(scaled_w, scaled_h, FilterType::Lanczos3);

    let crop_x = (scaled_w - WALL_W) / 2;
    let crop_y = (scaled_h - WALL_H) / 2;
    let cropped = image::imageops::crop_imm(&scaled, crop_x, crop_y, WALL_W, WALL_H)
        .to_image();
    let rgb_img = image::DynamicImage::ImageRgba8(cropped).to_rgb8();

    // Pack to row-major RGB (3 bytes/pixel).
    let mut rgb = Vec::with_capacity((WALL_W * WALL_H * 3) as usize);
    for pixel in rgb_img.pixels() {
        rgb.extend_from_slice(&pixel.0);
    }
    println!("cargo:warning=wallpaper cooked: {}x{} ({} KiB)",
             WALL_W, WALL_H, rgb.len() / 1024);

    std::fs::write(out_dir.join("wallpaper.bin"), &rgb)
        .expect("write wallpaper.bin");
    let wp_consts = format!(
        "// auto-generated by kernel/build.rs — do not edit\n\
         pub const WALLPAPER_W: usize = {};\n\
         pub const WALLPAPER_H: usize = {};\n",
        WALL_W, WALL_H
    );
    std::fs::write(out_dir.join("wallpaper_consts.rs"), wp_consts)
        .expect("write wallpaper_consts.rs");
}

/// Find the smallest (x, y, w, h) rectangle that contains every pixel whose
/// alpha is ≥ `cutoff`. Returns `None` if the image is fully transparent.
fn alpha_bbox(img: &RgbaImage, cutoff: u8) -> Option<(u32, u32, u32, u32)> {
    let (w, h) = img.dimensions();
    let mut min_x = w;
    let mut min_y = h;
    let mut max_x = 0u32;
    let mut max_y = 0u32;
    let mut any = false;
    for y in 0..h {
        for x in 0..w {
            if img.get_pixel(x, y)[3] >= cutoff {
                if !any {
                    min_x = x; max_x = x; min_y = y; max_y = y;
                    any = true;
                } else {
                    if x < min_x { min_x = x; }
                    if x > max_x { max_x = x; }
                    if y < min_y { min_y = y; }
                    if y > max_y { max_y = y; }
                }
            }
        }
    }
    if !any { return None; }
    Some((min_x, min_y, max_x - min_x + 1, max_y - min_y + 1))
}
